const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const concluir=(msg,novaFase)=>{msg.textContent='✨ Fase concluída! Próxima fase em instantes...';msg.classList.add('level-complete');setTimeout(()=>{msg.classList.remove('level-complete');novaFase()},1200)};
const mesa=[['✏️','Lápis','papelaria','Papelaria'],['🖊️','Caneta','papelaria','Papelaria'],['📏','Régua','papelaria','Papelaria'],['✂️','Tesoura','papelaria','Papelaria'],['📎','Clipes','papelaria','Papelaria'],['📒','Caderno','livros','Livros'],['📚','Livros','livros','Livros'],['📁','Pasta','livros','Livros'],['💻','Notebook','tecnologia','Tecnologia'],['🖱️','Mouse','tecnologia','Tecnologia'],['📱','Celular','tecnologia','Tecnologia'],['💡','Luminária','tecnologia','Tecnologia'],['🪴','Planta','decoracao','Decoração'],['🖼️','Porta-retrato','decoracao','Decoração'],['🌼','Flor','decoracao','Decoração'],['☕','Caneca','bebidas','Bebidas'],['💧','Água','bebidas','Bebidas'],['🧴','Álcool em gel','acessorios','Acessórios'],['🎧','Fone','acessorios','Acessórios'],['📌','Grampeador','acessorios','Acessórios']];
const jardim=[['🌷','Tulipa','flores','Flores'],['🌻','Girassol','flores','Flores'],['🌸','Flor','flores','Flores'],['🪴','Vaso','vasos','Vasos'],['🏺','Vaso alto','vasos','Vasos'],['🪨','Pedra','pedras','Pedras'],['◽','Seixo','pedras','Pedras'],['💧','Regador','cuidados','Cuidados'],['🧤','Luvas','cuidados','Cuidados'],['🌱','Muda','cuidados','Cuidados']];
function jogoClassificar(rootSel,pool,levelSel,itemsSel,zonesSel,msgSel){const root=document.querySelector(rootSel);if(!root)return;const tray=root.querySelector(itemsSel),zones=[...root.querySelectorAll(zonesSel)],msg=root.querySelector(msgSel),levelEl=root.querySelector(levelSel);let fase=1,sel=null,rest=0;const nova=()=>{levelEl.textContent=fase;tray.innerHTML='';sel=null;const qtd=Math.min(pool.length,5+fase);const itens=shuffle(pool).slice(0,qtd);rest=itens.length;itens.forEach(i=>{const b=document.createElement('button');b.type='button';b.className='game-piece';b.dataset.type=i[2];b.dataset.label=i[3];b.innerHTML=`<span>${i[0]}</span><small>${i[1]}</small>`;b.onclick=()=>{root.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));sel=b;b.classList.add('selected');msg.textContent=`Agora toque em “${i[3]}”.`};tray.append(b)});msg.textContent='Escolha um objeto para começar.'};zones.forEach(z=>z.onclick=()=>{if(!sel){msg.textContent='Primeiro toque em um objeto.';return}if(z.dataset.accept===sel.dataset.type){sel.classList.add('placed');sel.disabled=true;sel=null;rest--;if(rest===0){fase++;concluir(msg,nova)}else msg.textContent=`Muito bem! Faltam ${rest}.`}else{z.classList.add('wrong');setTimeout(()=>z.classList.remove('wrong'),400);msg.textContent='Tente outro espaço.'}});nova()}
document.addEventListener('DOMContentLoaded',()=>{
const bRoot=document.querySelector('[data-bubble-game]');if(bRoot){const board=bRoot.querySelector('[data-bubble-board]'),msg=bRoot.querySelector('[data-bubble-message]'),lvl=bRoot.querySelector('[data-bubble-level]');let fase=1;const nova=()=>{lvl.textContent=fase;board.innerHTML='';let total=Math.min(18+fase*3,42),rest=total;for(let i=0;i<total;i++){const b=document.createElement('button');b.type='button';b.className='bubble';b.style.setProperty('--size',`${38+Math.floor(Math.random()*30)}px`);b.setAttribute('aria-label','Estourar bolha');b.onclick=()=>{if(b.classList.contains('popped'))return;b.classList.add('popped');rest--;if(rest===0){fase++;concluir(msg,nova)}else msg.textContent=`${rest} bolhas restantes. Sem pressa.`};board.append(b)}msg.textContent='Uma bolha de cada vez.'};nova()}
const cRoot=document.querySelector('[data-color-game]');if(cRoot){const pal=cRoot.querySelector('[data-color-palette]'),seq=cRoot.querySelector('[data-color-sequence]'),msg=cRoot.querySelector('[data-color-message]'),lvl=cRoot.querySelector('[data-color-level]');let fase=1;const fam=[['#fde8ef','#f9b9cf','#f47da7','#df3e75','#9f1749','#6d1032'],['#e8f1ff','#b7d2ff','#79a8f5','#3f72cf','#244693','#15295f'],['#eaf8e9','#bde7b9','#82c879','#4c9d4b','#28622d','#163b1b'],['#fff4dd','#ffdca1','#ffb95c','#e98522','#9f4b10','#642f0a']];const lum=x=>{x=x.slice(1);return.2126*parseInt(x.slice(0,2),16)+.7152*parseInt(x.slice(2,4),16)+.0722*parseInt(x.slice(4,6),16)};const nova=()=>{lvl.textContent=fase;const qtd=Math.min(4+fase,6),cores=shuffle(fam[Math.floor(Math.random()*fam.length)]).slice(0,qtd),ord=[...cores].sort((a,b)=>lum(b)-lum(a));let passo=0;pal.innerHTML='';seq.innerHTML='';cores.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='color-piece';b.style.background=c;b.onclick=()=>{if(b.disabled)return;if(c===ord[passo]){b.disabled=true;b.classList.add('used');const s=document.createElement('span');s.style.background=c;seq.append(s);passo++;if(passo===ord.length){fase++;concluir(msg,nova)}else msg.textContent='Continue da mais clara para a mais escura.'}else{b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),400);msg.textContent='Tente uma cor mais clara.'}};pal.append(b)});msg.textContent='Comece pela peça mais clara.'};nova()}
jogoClassificar('[data-organize-game]',mesa,'[data-organize-level]','[data-organize-items]','.sort-zone','[data-organize-message]');
jogoClassificar('[data-garden-game]',jardim,'[data-garden-level]','[data-garden-items]','.garden-zone','[data-garden-message]');
});